#!/bin/sh
set -eu

#SCHEMESCRIPT=".akku/env guile -x .guile.sls -x .sls"
SCHEMESCRIPT=".akku/env"

$SCHEMESCRIPT bin/akku.sps dependency-scan --implementation=guile bin/akku.sps > guile-deps.txt

datadir=${XDG_DATA_HOME:-~/.local/share}

mkdir -p "$datadir"/akku/keys.d
cp akku-archive-*.gpg "$datadir"/akku/keys.d

[ -f "$datadir"/akku/index.db ] || $SCHEMESCRIPT bin/akku.sps update
[ -f bootstrap.db ] || cp "$datadir"/akku/index.db bootstrap.db

autoreconf --verbose --install --force
